SET HOME=..
SET WII_SDK_HOME=%HOME%\RVL_SDK
SET RAW_ISO_EXTRACTED_DIR=..\extract_game\REVOLUTION
SET OUT_DIR=%HOME%\out
SET IMG_DIR=%HOME%\img
SET TEXT_DIR=%HOME%\text
SET BIN_DIR=%HOME%\bin
SET TMP_DIR=%HOME%\tmp
SET TMP_IMG_DIR=%TMP_DIR%\img
SET RAW_ISO=..\..\su-acr.iso

