SET HOME=..
SET WII_SDK_HOME=%HOME%\RVL_SDK
SET OUT_DIR=%HOME%\out
SET TEXT_DIR=%HOME%\text
SET BIN_DIR=%HOME%\bin
SET TMP_DIR=%HOME%\tmp
SET EXTRACT_DIR=%HOME%\extract
SET RAW_ISO=..\..\su-acr.iso
