bmg.exe MESS/MESS1.xml out/patch/MESS1.bmg
bmg.exe MESS/MESS2.xml out/patch/MESS2.bmg
bmg.exe MESS/MESS3.xml out/patch/MESS3.bmg
bmg.exe MESS/MESS4.xml out/patch/MESS4.bmg
bmg.exe MESS/MESS5.xml out/patch/MESS5.bmg
bmg.exe MESS/MESS6.xml out/patch/MESS6.bmg
bmg.exe MESS/MESS7.xml out/patch/MESS7.bmg
bmg.exe MESS/MESS8.xml out/patch/MESS8.bmg
bmg.exe MESS/MESS9.xml out/patch/MESS9.bmg

bmg.exe PUZZLE/PUZZLE_MESS_002.xml out/patch/PUZZLE_MESS_002.bmg
bmg.exe PUZZLE/PUZZLE_MESS_003.xml out/patch/PUZZLE_MESS_003.bmg
bmg.exe PUZZLE/PUZZLE_MESS_005.xml out/patch/PUZZLE_MESS_005.bmg
bmg.exe PUZZLE/PUZZLE_MESS_006.xml out/patch/PUZZLE_MESS_006.bmg
bmg.exe PUZZLE/PUZZLE_MESS_012.xml out/patch/PUZZLE_MESS_012.bmg
bmg.exe PUZZLE/PUZZLE_MESS_013.xml out/patch/PUZZLE_MESS_013.bmg
bmg.exe PUZZLE/PUZZLE_MESS_014.xml out/patch/PUZZLE_MESS_014.bmg
bmg.exe PUZZLE/PUZZLE_MESS_017.xml out/patch/PUZZLE_MESS_017.bmg
bmg.exe PUZZLE/PUZZLE_MESS_022.xml out/patch/PUZZLE_MESS_022.bmg
bmg.exe PUZZLE/PUZZLE_MESS_025.xml out/patch/PUZZLE_MESS_025.bmg
bmg.exe PUZZLE/PUZZLE_MESS_027.xml out/patch/PUZZLE_MESS_027.bmg
bmg.exe PUZZLE/PUZZLE_MESS_028.xml out/patch/PUZZLE_MESS_028.bmg
bmg.exe PUZZLE/PUZZLE_MESS_032.xml out/patch/PUZZLE_MESS_032.bmg
bmg.exe PUZZLE/PUZZLE_MESS_035.xml out/patch/PUZZLE_MESS_035.bmg
bmg.exe PUZZLE/PUZZLE_MESS_037.xml out/patch/PUZZLE_MESS_037.bmg
bmg.exe PUZZLE/PUZZLE_MESS_041.xml out/patch/PUZZLE_MESS_041.bmg
bmg.exe PUZZLE/PUZZLE_MESS_042.xml out/patch/PUZZLE_MESS_042.bmg
bmg.exe PUZZLE/PUZZLE_MESS_043.xml out/patch/PUZZLE_MESS_043.bmg
bmg.exe PUZZLE/PUZZLE_MESS_049.xml out/patch/PUZZLE_MESS_049.bmg
bmg.exe PUZZLE/PUZZLE_MESS_050.xml out/patch/PUZZLE_MESS_050.bmg
bmg.exe PUZZLE/PUZZLE_MESS_051.xml out/patch/PUZZLE_MESS_051.bmg
bmg.exe PUZZLE/PUZZLE_MESS_052.xml out/patch/PUZZLE_MESS_052.bmg
bmg.exe PUZZLE/PUZZLE_MESS_056.xml out/patch/PUZZLE_MESS_056.bmg
bmg.exe PUZZLE/PUZZLE_MESS_057.xml out/patch/PUZZLE_MESS_057.bmg
bmg.exe PUZZLE/PUZZLE_MESS_059.xml out/patch/PUZZLE_MESS_059.bmg
bmg.exe PUZZLE/PUZZLE_MESS_060.xml out/patch/PUZZLE_MESS_060.bmg
bmg.exe PUZZLE/PUZZLE_MESS_061.xml out/patch/PUZZLE_MESS_061.bmg
bmg.exe PUZZLE/PUZZLE_MESS_069.xml out/patch/PUZZLE_MESS_069.bmg
bmg.exe PUZZLE/PUZZLE_MESS_070.xml out/patch/PUZZLE_MESS_070.bmg
bmg.exe PUZZLE/PUZZLE_MESS_071.xml out/patch/PUZZLE_MESS_071.bmg
bmg.exe PUZZLE/PUZZLE_MESS_072.xml out/patch/PUZZLE_MESS_072.bmg
bmg.exe PUZZLE/PUZZLE_MESS_075.xml out/patch/PUZZLE_MESS_075.bmg
bmg.exe PUZZLE/PUZZLE_MESS_076.xml out/patch/PUZZLE_MESS_076.bmg
bmg.exe PUZZLE/PUZZLE_MESS_078.xml out/patch/PUZZLE_MESS_078.bmg
bmg.exe PUZZLE/PUZZLE_MESS_079.xml out/patch/PUZZLE_MESS_079.bmg
bmg.exe PUZZLE/PUZZLE_MESS_081.xml out/patch/PUZZLE_MESS_081.bmg

bmg.exe SYSTEM/HISTORY.xml out/patch/HISTORY.bmg
bmg.exe SYSTEM/LOAD_HISTORY.xml out/patch/LOAD_HISTORY.bmg
bmg.exe SYSTEM/SYSTEM1.xml out/patch/SYSTEM1.bmg
bmg.exe SYSTEM/SYSTEM2.xml out/patch/SYSTEM2.bmg
bmg.exe SYSTEM/SYSTEM3.xml out/patch/SYSTEM3.bmg
bmg.exe SYSTEM/SYSTEM4.xml out/patch/SYSTEM4.bmg
bmg.exe SYSTEM/SYSTEM5.xml out/patch/SYSTEM5.bmg
bmg.exe SYSTEM/SYSTEM6.xml out/patch/SYSTEM6.bmg
bmg.exe SYSTEM/SYSTEM7.xml out/patch/SYSTEM7.bmg
bmg.exe SYSTEM/SYSTEM8.xml out/patch/SYSTEM8.bmg
bmg.exe SYSTEM/SYSTEM9.xml out/patch/SYSTEM9.bmg

pause